### ISSUE TITLE
Implementar clase Revista

### ISSUE THREAD

**Issue by ariktaurendil** [softwareperonista/canillita#2]
Implementar la clase Revista como parte del [CU-01](https://github.com/softwareperonista/canillita/wiki/Caso-De-Uso-1---Consulta-Revista) 

Debe heredar de GLib.Object

Miembros
========

Tipo | Nombre
------|----------
uint64 | codigo_de_barras
string | nombre
float | precio_de_compra
float | precio_de_venta
uint | numero
uint | anio

Todos los miembros definidos como public.

Necesario para cerrar #1

**Comment by tarmaciltur** [comment]
Revista no debería heredar de la clase Artículo? Es decir, me parece mejor separar en una clase todos las variables miembro y los métodos que se repitan en todos los artículos.

**Comment by ariktaurendil** [comment]
Sí, eso lo vamos a implementar, pero para poder hacer este caso de uso lo más simple que se pueda, preferimos no agregar, por el momento, esa compljidad. Claro que el próximo paso una vez que cerremos #1 va a ser la clase Artículo.
