### ISSUE TITLE
Implementar UI según CU-01

### ISSUE THREAD

**Issue by ariktaurendil** [softwareperonista/canillita#5]
Implementar según PAN-01 y PAN-02 de [CU-01](https://github.com/softwareperonista/canillita/wiki/Caso-De-Uso-1---Consulta-Revista)

PAN-01
![PAN-01](https://cloud.githubusercontent.com/assets/1479841/7439708/d7e499e4-f05c-11e4-881c-f0e6b2898372.png)

PAN-02
![captura de pantalla de 2015-06-15 21-03-26](https://cloud.githubusercontent.com/assets/1479841/8173327/169414cc-13a2-11e5-9800-74c18753c3ed.png)

Necesario para cerrar #1

**Comment by ariktaurendil** [comment]
El TreeView de Revistas debería tener además la columba de años y número, para diferenciar el stock de revistas por su edición.

**Comment by ariktaurendil** [comment]
Canillita.Revista tiene los campos precio_de_venta y  precio_de_compra. Debería poner esos campos como columnas del treeview del stock?

**Comment by Calevin** [comment]
Según entiendo yo, si, de igual manera que el resto de la información de Canillita.Revista, ¿hay alguna razón por lo que estos datos deberían ser tratados de manera distinta?.

**Comment by ariktaurendil** [comment]
No sé, quizás puede quedar con demasiada información. Se puede pensar otra forma de mostrar la información completa. Por eso lo pensaba. Pero no hay un motivo fuerte para que sea así.

**Comment by tarmaciltur** [comment]
Yo creo que deberían ir.
